#+AUTHOR:
#+TITLE:
#+OPTIONS:     toc:nil num:nil
#+LATEX_HEADER: \usepackage{mathrsfs}
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_HEADER: \usepackage{booktabs}
#+LATEX_HEADER: \usepackage{dcolumn}
#+LATEX_HEADER: \usepackage{subfigure}
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \usepackage{color}
#+LATEX_HEADER: \RequirePackage{fancyvrb}
#+LATEX_HEADER: \DefineVerbatimEnvironment{verbatim}{Verbatim}{fontsize=\small,formatcom = {\color[rgb]{0.1,0.2,0.9}}}
#+LATEX: \renewcommand{\P}{{\bf P}}
#+LATEX: \newcommand{\ep}{{\bf e}^\prime}
#+LATEX: \newcommand{\e}{{\bf e}}
#+LATEX: \newcommand{\I}{{\bf I}}
#+LATEX: \newcommand{\W}{{\bf W}}
#+LATEX: \newcommand{\w}{{\bf w}}
#+LATEX: \newcommand{\X}{{\bf X}}
#+LATEX: \newcommand{\x}{{\bf x}}
#+LATEX: \newcommand{\Y}{{\bf Y}}
#+LATEX: \newcommand{\y}{{\bf y}}
#+LATEX: \newcommand{\Z}{{\bf Z}}
#+LATEX: \newcommand{\z}{{\bf z}}
#+LATEX: \newcommand{\M}{{\bf M}}
#+LATEX: \newcommand{\A}{{\bf A}}
#+LATEX: \newcommand{\Ap}{{\bf A}^{\prime}}
#+LATEX: \newcommand{\B}{{\bf B}}
#+LATEX: \newcommand{\Bp}{{\bf B}^{\prime}}
#+LATEX: \newcommand{\Xp}{{\bf X}^{\prime}}
#+LATEX: \newcommand{\Mp}{{\bf M}^{\prime}}
#+LATEX: \newcommand{\yp}{{\bf y}^{\prime}}
#+LATEX: \newcommand{\yh}{\hat{{\bf y}}}
#+LATEX: \newcommand{\yhp}{\hat{{\bf y}}^{\prime}}
#+LATEX: \newcommand{\In}{{\bf I}_n}
#+LATEX: \newcommand{\email}[1]{\textcolor{blue}{\texttt{#1}}}
#+LATEX: \newcommand{\id}[1]{{\bf I}_{#1}}
#+LATEX: \newcommand{\myheader}[1]{\textcolor{black}{\textbf{#1}}}
#+LATEX: \setlength{\parindent}{0in}
#+STARTUP: fninline

*Matrix operations in =R=* \hfill
*ARE212*: Section 02 \\ \hline \bigskip

This section continues where we left off last week, introducing you to increasingly complex matrix manipulation in =R= and finishing with some puzzles in =R=. Soon we'll move on to real life data, I promise. But for now... matrices!



* Linear algebra puzzles

1. Define vectors $\x = [1 \hspace{6pt} 2 \hspace{6pt} 3]'$, $\y = [2 \hspace{6pt} 3 \hspace{6pt} 4]'$, and $\z = [3 \hspace{6pt} 5 \hspace{6pt} 7]$. Define $\W = [\x \hspace{6pt} \y \hspace{6pt} \z]$.  Calculate $\W^{-1}$.  If you cannot take the inverse, explain why not and adjust $\W$ so that you /can/ take the inverse. /Hint/: the =solve()= function will return the inverse of the supplied matrices.

2. Show, somehow, that $(\Xp)^{-1} = (\X^{-1})^{\prime}$.

3. Generate a $3 \times 3$ matrix $\X$, where each element is drawn from a standard normal distribution.  Let $\A = \I_3 - \frac{1}{3}\B$ be a demeaning matrix, with $\i$ a $3 \times 3$ matrix of ones.  First show that $\A$ is idempotent and symmetric. Next show that each row of the matrix $\X\A$ is the deviation of each row in $\X$ from its mean.  Finally, show that $(\X\A)(\X\A)^{\prime} = \X\A\Xp$, first through algebra and then =R= code.

4. Demonstrate from random matrices that $(\X\Y\Z)^{-1} = \Z^{-1}\Y^{-1}\X^{-1}$.

5. Let $\X$ and $\Y$ be square $20 \times 20$ matrices.  Show that $tr(\X + \Y) = tr(\X) + tr(\Y)$.

6. Generate a diagonal matrix $\X$, where each element on the diagnonal is drawn from $U[10,20]$. Now generate a matrix $\B$ s.t. $\X = \B\Bp$. /Hint/: There is a method in =R= that makes this easy. Does the fact that you can generate $\B$ tell you anything about $\X$?

7. Demonstrate that for any scalar $c$ and any square matrix $\X$ of dimension $n$ that $\det(c\X) = c^n \det(\X)$.

8. Demonstrate that for an $m \times m$ matrix $\A$ and a $p \times p$ matrix $\B$ that $\det(\A \otimes \B) = \det(\A)^p \det(\B)^m$. /Hint/: Note that $\otimes$ indicates the Kronecker product\footnote{The Kronecker product is a useful mathemagical tool for econometricians, allowing us to more easily describe block-diagonal matricees for use in panel data settings. I wouldn't lose sleep over it, though.}.  Google the appropriate =R= function.

#+BEGIN_SRC R :results graphics output :exports none :tangle yes

## Dan Hammer
## ARE212, Spring 2012
## Linear Algebra Puzzles

## Question 1

X <- c(1,2,3)
Y <- c(2,3,4)
Z <- c(3,5,7)

## The vector Z is a linear combination of X and Y, and R will throw
## an error when taking the inverse
W <- cbind(X, Y, Z)
solve(W)

## Replace an element to invert the matrix W
W[1,1] <- 4
solve(W)

## Question 2

X <- matrix(rnorm(9), nrow = 3)
all.equal(solve(t(X)), t(solve(X)))

## Question 3

i <- matrix(c(1,1,1))
A <- diag(3) - (1/3)* i %*% t(i)

demeaned <- X %*% A
all.equal(X[1, ] - mean(X[1,]), demeaned[1,])
all.equal(X[2, ] - mean(X[2,]), demeaned[2,])
all.equal(X[3, ] - mean(X[3,]), demeaned[3,])

## Question 4

X <- matrix(rnorm(9), 3)
Y <- matrix(rnorm(9), 3)
Z <- matrix(rnorm(9), 3)

c <- solve(X %*% Y %*% Z)
d <- solve(Z) %*% solve(Y) %*% solve(X)
all.equal(c, d)

## Question 5

X <- matrix(rnorm(400), 20)
Y <- matrix(rnorm(400), 20)

f <- sum(diag(X + Y))
g <- sum(diag(X)) + sum(diag(Y))
all.equal(f, g)

## Question 6

X <- diag(runif(10, min = 10, max = 20))
B <- chol(X)
all.equal(B %*% t(B), X)
# Per #20 on the linear algebra review, X must be positive semi-definite

## Question 7

c <- 5
n <- 3
X <- matrix(rnorm(9), nrow = n)
all.equal(det(c * X), c^n * det(X))

## Question 8

X <- matrix(runif(9), 3)
Y <- matrix(runif(16), 4)
h <- det(kronecker(X, Y))
j <- det(X)^4 * det(Y)^3
all.equal(h, j)

#+END_SRC

#+RESULTS:

